# Generated by Django 2.0.2 on 2018-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('PriorBalance', models.IntegerField()),
                ('NewBalance', models.IntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
