# Generated by Django 2.0.2 on 2018-02-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20180213_1233'),
        ('accounts', '0001_initial'),
        ('service', '0003_auto_20180213_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='accounts.driver'),
        ),
        migrations.AddField(
            model_name='request',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='policies.policy'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic', to='service.Mechanic'),
        ),
    ]
