# Generated by Django 2.0.2 on 2018-02-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make_claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuster',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='make_claims.Claims')),
            ],
        ),
    ]
