# Generated by Django 2.0.2 on 2018-02-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_claims', '0001_initial'),
        ('adjusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='make_claims.Claims'),
        ),
    ]
