# Generated by Django 2.0.2 on 2018-02-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make_claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Spcific_Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disconts_table',
            fields=[
                ('Discount_Name', models.CharField(max_length=20)),
                ('points_required', models.IntegerField()),
                ('Cupon_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='General_Discounts',
            fields=[
                ('Discount_Name', models.CharField(max_length=20)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Cupon_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer_spcific_discounts',
            name='Discount_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discounts.Disconts_table'),
        ),
        migrations.AddField(
            model_name='customer_spcific_discounts',
            name='Policy_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_claims.Policy'),
        ),
    ]
