# Generated by Django 2.0.2 on 2018-02-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('corporation', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=50)),
                ('license_plate_num', models.CharField(max_length=7)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'prefer not to answer')], default='n', max_length=1)),
                ('active_driver', models.CharField(choices=[('LP', 'Learners Permits'), ('DL', 'Drivers License'), ('R', 'Revoked'), ('S', 'Suspended')], max_length=2)),
                ('driver_state_of_residence', models.CharField(max_length=50)),
                ('num_of_collisions', models.IntegerField(default=0)),
                ('first_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstname', to='accounts.account')),
                ('last_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastname', to='accounts.account')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='username', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('car_model', models.CharField(choices=[('T', 'Toyota'), ('N', 'Nissan'), ('F', 'Ford'), ('VB', 'Volkswagon Beetle'), ('J', 'Jeep'), ('C', 'Chrysler'), ('CH', 'Chevrolet'), ('AU', 'Audi'), ('AM', 'Aston Martin'), ('AC', 'Acura'), ('B', 'BMW'), ('CD', 'Cadillac'), ('CR', 'Corvette'), ('D', 'Dodge'), ('G', 'GMC'), ('HN', 'Honda'), ('HY', 'Hyundai'), ('HM', 'Hummer'), ('IS', 'Isuzu'), ('IN', 'Infiniti'), ('JG', 'Jaguar'), ('LM', 'Lamborghini'), ('LR', 'Landrover'), ('LN', 'Lincoln')], max_length=50)),
                ('year_of_purchase', models.CharField(choices=[('20th Century', '1900-1999'), ('21th Century', '2000-2099')], max_length=12)),
                ('car_color', models.CharField(choices=[('R', 'Red'), ('BL', 'Blue'), ('G', 'Green'), ('WH', 'White'), ('G', 'Grey'), ('BLK', 'Black'), ('P', 'Pink'), ('PR', 'Purple'), ('Y', 'Yellow')], max_length=10)),
                ('car_condition', models.CharField(choices=[('G', 'Good Condition'), ('NG', 'Not So Good Condition'), ('B', 'Bad Condition'), ('T', 'Totaled')], max_length=50)),
                ('car_condition_details', models.TextField(blank=True, max_length=100, null=True)),
                ('car_mileage', models.CharField(choices=[('LOW', '0-10000'), ('NORMAL', '10000-50000'), ('HIGH', '50000-100000')], max_length=20)),
                ('vehicle_num', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('purchase_date', models.DateField()),
                ('miles_per_year', models.CharField(choices=[('LOW', '0-100'), ('NORMAL', '100-200'), ('HIGH', '200-300')], max_length=10)),
            ],
        ),
    ]
