# Generated by Django 2.0.2 on 2018-02-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Username', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_purchase',
            field=models.CharField(choices=[('20th Century', '1900-1999'), ('21th Century', '2000-2099')], max_length=12),
        ),
    ]
