# Generated by Django 2.0.1 on 2018-02-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('Claimed_Date', models.DateField()),
                ('Claim_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Other_party_Name', models.CharField(max_length=100)),
                ('Other_party_Insurance_company_Name', models.CharField(max_length=100)),
                ('Other_party_policy_Number', models.CharField(max_length=100)),
                ('Other_party_Phone_Number', models.CharField(max_length=100)),
                ('Claim_Resolved_Date', models.DateField(blank=True, null=True)),
                ('Description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('Policy_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vechicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
