# Generated by Django 2.0.2 on 2018-02-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('Claimed_Date', models.DateField()),
                ('Claim_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Other_party_Name', models.CharField(max_length=100)),
                ('Other_party_Insurance_company_Name', models.CharField(max_length=100)),
                ('Other_party_policy_Number', models.CharField(max_length=100)),
                ('Other_party_Phone_Number', models.CharField(max_length=100)),
                ('Claim_Resolved_Date', models.DateField(blank=True, null=True)),
                ('Description', models.CharField(max_length=3000)),
                ('Status', models.CharField(blank=True, max_length=500, null=True)),
                ('Policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_policy', to='policies.policy')),
            ],
        ),
    ]
