# Generated by Django 2.0.1 on 2018-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
