# Generated by Django 2.0.2 on 2018-02-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_plan', models.CharField(choices=[('LC', 'Liability Coverage'), ('CC', 'Collision Coverage'), ('COM', 'Comprehensive Coverage'), ('UN', 'Uninsured/Underinsured Motorist Coverage'), ('MP', 'Medical Payments'), ('PIP', 'Personal Injury Protection')], max_length=100)),
                ('payments_made', models.IntegerField(default=0)),
                ('total_rate', models.PositiveSmallIntegerField()),
                ('payment_plan', models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('W', 'Weekly')], default='Yearly', max_length=10)),
                ('payment_due_date', models.DateTimeField()),
                ('payment', models.PositiveSmallIntegerField(default=0)),
                ('actual_date_of_payment', models.DateTimeField()),
                ('suspended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('points', models.IntegerField(default=0)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
