# Generated by Django 2.0.2 on 2018-02-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now=True)),
                ('payments_made', models.IntegerField(default=0)),
                ('total_rate', models.DecimalField(choices=[('12000.00', 'Full'), ('6000.00', 'Half'), ('3000.00', 'Liability')], decimal_places=2, max_digits=8)),
                ('payment_plan', models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('W', 'Weekly')], default='Yearly', max_length=1)),
                ('payment_due_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suspended', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='accounts.account')),
            ],
        ),
    ]
