# Generated by Django 2.0.2 on 2018-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='payment_plan',
            field=models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1),
        ),
    ]
