# Generated by Django 2.0.2 on 2018-02-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='id',
        ),
        migrations.AlterField(
            model_name='policy',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='user_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account'),
        ),
    ]
