# Generated by Django 2.0.2 on 2018-02-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20180219_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='total_rate',
            field=models.DecimalField(choices=[(12000.0, 'Full'), (6000.0, 'Half'), (3000.0, 'Liability')], decimal_places=2, max_digits=8),
        ),
    ]
