# Generated by Django 2.0.2 on 2018-02-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180216_1109'),
        ('policies', '0002_remove_policy_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CarModel', to='accounts.vehicle'),
        ),
        migrations.AddField(
            model_name='policy',
            name='first_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Driver', to='accounts.driver'),
        ),
    ]
